apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: my-golf
type: Opaque
stringData:
  POSTGRES_USER: mygolf
  POSTGRES_PASSWORD: mygolf
  POSTGRES_DB: mygolf
  DATABASE_URL: postgresql+asyncpg://mygolf:mygolf@db:5432/mygolf
